// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2667.TestRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightMotor;
    public static SpeedController driveTrainLeftMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static AnalogInput driveTrainUltrasonic;
    public static SpeedController elevatorMotor;
    public static AnalogPotentiometer elevatorPot;
    public static SpeedController wristMotor;
    public static AnalogPotentiometer wristPot;
    public static SpeedController clawMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightMotor = new Jaguar(1);
        LiveWindow.addActuator("Drive Train", "Right Motor", (Jaguar) driveTrainRightMotor);
        
        driveTrainLeftMotor = new Jaguar(2);
        LiveWindow.addActuator("Drive Train", "Left Motor", (Jaguar) driveTrainLeftMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainRightMotor, driveTrainLeftMotor);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        

        driveTrainUltrasonic = new AnalogInput(3);
        LiveWindow.addSensor("Drive Train", "Ultrasonic", driveTrainUltrasonic);
        
        elevatorMotor = new Talon(6);
        LiveWindow.addActuator("Elevator", "Motor", (Talon) elevatorMotor);
        
        elevatorPot = new AnalogPotentiometer(4, 1.0, 0.0);
        LiveWindow.addSensor("Elevator", "Pot", elevatorPot);
        
        wristMotor = new Talon(7);
        LiveWindow.addActuator("Wrist", "Motor", (Talon) wristMotor);
        
        wristPot = new AnalogPotentiometer(2, 1.0, 0.0);
        LiveWindow.addSensor("Wrist", "Pot", wristPot);
        
        clawMotor = new Talon(5);
        LiveWindow.addActuator("Claw", "Motor", (Talon) clawMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
